//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertSystem.ServiceRefHealth {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SNSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Value1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.BP bpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int oldSNSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientID {
            get {
                return this.PatientIDField;
            }
            set {
                if ((this.PatientIDField.Equals(value) != true)) {
                    this.PatientIDField = value;
                    this.RaisePropertyChanged("PatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SNS {
            get {
                return this.SNSField;
            }
            set {
                if ((this.SNSField.Equals(value) != true)) {
                    this.SNSField = value;
                    this.RaisePropertyChanged("SNS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value1 {
            get {
                return this.Value1Field;
            }
            set {
                if ((this.Value1Field.Equals(value) != true)) {
                    this.Value1Field = value;
                    this.RaisePropertyChanged("Value1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.BP bps {
            get {
                return this.bpsField;
            }
            set {
                if ((object.ReferenceEquals(this.bpsField, value) != true)) {
                    this.bpsField = value;
                    this.RaisePropertyChanged("bps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int oldSNS {
            get {
                return this.oldSNSField;
            }
            set {
                if ((this.oldSNSField.Equals(value) != true)) {
                    this.oldSNSField = value;
                    this.RaisePropertyChanged("oldSNS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BP", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class BP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Utente UtenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Valor1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Valor2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alerta {
            get {
                return this.AlertaField;
            }
            set {
                if ((this.AlertaField.Equals(value) != true)) {
                    this.AlertaField = value;
                    this.RaisePropertyChanged("Alerta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Utente Utente {
            get {
                return this.UtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UtenteField, value) != true)) {
                    this.UtenteField = value;
                    this.RaisePropertyChanged("Utente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor1 {
            get {
                return this.Valor1Field;
            }
            set {
                if ((this.Valor1Field.Equals(value) != true)) {
                    this.Valor1Field = value;
                    this.RaisePropertyChanged("Valor1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor2 {
            get {
                return this.Valor2Field;
            }
            set {
                if ((this.Valor2Field.Equals(value) != true)) {
                    this.Valor2Field = value;
                    this.RaisePropertyChanged("Valor2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utente", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Utente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Alerta[] AlertasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApelidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.BP[] BPsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataNascField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.HR[] HRsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUtenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SNSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.SPO[] SPOesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Alerta[] Alertas {
            get {
                return this.AlertasField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertasField, value) != true)) {
                    this.AlertasField = value;
                    this.RaisePropertyChanged("Alertas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apelido {
            get {
                return this.ApelidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApelidoField, value) != true)) {
                    this.ApelidoField = value;
                    this.RaisePropertyChanged("Apelido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.BP[] BPs {
            get {
                return this.BPsField;
            }
            set {
                if ((object.ReferenceEquals(this.BPsField, value) != true)) {
                    this.BPsField = value;
                    this.RaisePropertyChanged("BPs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataNasc {
            get {
                return this.DataNascField;
            }
            set {
                if ((this.DataNascField.Equals(value) != true)) {
                    this.DataNascField = value;
                    this.RaisePropertyChanged("DataNasc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.HR[] HRs {
            get {
                return this.HRsField;
            }
            set {
                if ((object.ReferenceEquals(this.HRsField, value) != true)) {
                    this.HRsField = value;
                    this.RaisePropertyChanged("HRs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUtente {
            get {
                return this.IdUtenteField;
            }
            set {
                if ((this.IdUtenteField.Equals(value) != true)) {
                    this.IdUtenteField = value;
                    this.RaisePropertyChanged("IdUtente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdadeField, value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SNS {
            get {
                return this.SNSField;
            }
            set {
                if ((this.SNSField.Equals(value) != true)) {
                    this.SNSField = value;
                    this.RaisePropertyChanged("SNS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.SPO[] SPOes {
            get {
                return this.SPOesField;
            }
            set {
                if ((object.ReferenceEquals(this.SPOesField, value) != true)) {
                    this.SPOesField = value;
                    this.RaisePropertyChanged("SPOes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alerta", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Alerta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParametroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Utente UtenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parametro {
            get {
                return this.ParametroField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametroField, value) != true)) {
                    this.ParametroField = value;
                    this.RaisePropertyChanged("Parametro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Utente Utente {
            get {
                return this.UtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UtenteField, value) != true)) {
                    this.UtenteField = value;
                    this.RaisePropertyChanged("Utente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HR", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class HR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Utente UtenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alerta {
            get {
                return this.AlertaField;
            }
            set {
                if ((this.AlertaField.Equals(value) != true)) {
                    this.AlertaField = value;
                    this.RaisePropertyChanged("Alerta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Utente Utente {
            get {
                return this.UtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UtenteField, value) != true)) {
                    this.UtenteField = value;
                    this.RaisePropertyChanged("Utente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SPO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class SPO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Utente UtenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alerta {
            get {
                return this.AlertaField;
            }
            set {
                if ((this.AlertaField.Equals(value) != true)) {
                    this.AlertaField = value;
                    this.RaisePropertyChanged("Alerta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Utente Utente {
            get {
                return this.UtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UtenteField, value) != true)) {
                    this.UtenteField = value;
                    this.RaisePropertyChanged("Utente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BPs", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class BPs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SNSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Value1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Value2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Patient patientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sns1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alert {
            get {
                return this.AlertField;
            }
            set {
                if ((this.AlertField.Equals(value) != true)) {
                    this.AlertField = value;
                    this.RaisePropertyChanged("Alert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SNS {
            get {
                return this.SNSField;
            }
            set {
                if ((this.SNSField.Equals(value) != true)) {
                    this.SNSField = value;
                    this.RaisePropertyChanged("SNS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value1 {
            get {
                return this.Value1Field;
            }
            set {
                if ((this.Value1Field.Equals(value) != true)) {
                    this.Value1Field = value;
                    this.RaisePropertyChanged("Value1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value2 {
            get {
                return this.Value2Field;
            }
            set {
                if ((this.Value2Field.Equals(value) != true)) {
                    this.Value2Field = value;
                    this.RaisePropertyChanged("Value2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Patient patient {
            get {
                return this.patientField;
            }
            set {
                if ((object.ReferenceEquals(this.patientField, value) != true)) {
                    this.patientField = value;
                    this.RaisePropertyChanged("patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="sns")]
        public int sns1 {
            get {
                return this.sns1Field;
            }
            set {
                if ((this.sns1Field.Equals(value) != true)) {
                    this.sns1Field = value;
                    this.RaisePropertyChanged("sns1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SPOes", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class SPOes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SNSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Patient patientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sns1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alert {
            get {
                return this.AlertField;
            }
            set {
                if ((this.AlertField.Equals(value) != true)) {
                    this.AlertField = value;
                    this.RaisePropertyChanged("Alert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SNS {
            get {
                return this.SNSField;
            }
            set {
                if ((this.SNSField.Equals(value) != true)) {
                    this.SNSField = value;
                    this.RaisePropertyChanged("SNS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Patient patient {
            get {
                return this.patientField;
            }
            set {
                if ((object.ReferenceEquals(this.patientField, value) != true)) {
                    this.patientField = value;
                    this.RaisePropertyChanged("patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="sns")]
        public int sns1 {
            get {
                return this.sns1Field;
            }
            set {
                if ((this.sns1Field.Equals(value) != true)) {
                    this.sns1Field = value;
                    this.RaisePropertyChanged("sns1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HRs", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class HRs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SNSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Patient patientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sns1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alert {
            get {
                return this.AlertField;
            }
            set {
                if ((this.AlertField.Equals(value) != true)) {
                    this.AlertField = value;
                    this.RaisePropertyChanged("Alert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SNS {
            get {
                return this.SNSField;
            }
            set {
                if ((this.SNSField.Equals(value) != true)) {
                    this.SNSField = value;
                    this.RaisePropertyChanged("SNS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Patient patient {
            get {
                return this.patientField;
            }
            set {
                if ((object.ReferenceEquals(this.patientField, value) != true)) {
                    this.patientField = value;
                    this.RaisePropertyChanged("patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="sns")]
        public int sns1 {
            get {
                return this.sns1Field;
            }
            set {
                if ((this.sns1Field.Equals(value) != true)) {
                    this.sns1Field = value;
                    this.RaisePropertyChanged("sns1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alertas", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Alertas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.BPs BpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.HRs HrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.Patient PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SNSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlertSystem.ServiceRefHealth.SPOes SpoeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alert {
            get {
                return this.AlertField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertField, value) != true)) {
                    this.AlertField = value;
                    this.RaisePropertyChanged("Alert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.BPs Bp {
            get {
                return this.BpField;
            }
            set {
                if ((object.ReferenceEquals(this.BpField, value) != true)) {
                    this.BpField = value;
                    this.RaisePropertyChanged("Bp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.HRs Hr {
            get {
                return this.HrField;
            }
            set {
                if ((object.ReferenceEquals(this.HrField, value) != true)) {
                    this.HrField = value;
                    this.RaisePropertyChanged("Hr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.Patient Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SNS {
            get {
                return this.SNSField;
            }
            set {
                if ((this.SNSField.Equals(value) != true)) {
                    this.SNSField = value;
                    this.RaisePropertyChanged("SNS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlertSystem.ServiceRefHealth.SPOes Spoe {
            get {
                return this.SpoeField;
            }
            set {
                if ((object.ReferenceEquals(this.SpoeField, value) != true)) {
                    this.SpoeField = value;
                    this.RaisePropertyChanged("Spoe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLayer")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRefHealth.IServiceHealth")]
    public interface IServiceHealth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddPatient", ReplyAction="http://tempuri.org/IServiceHealth/AddPatientResponse")]
        bool AddPatient(AlertSystem.ServiceRefHealth.Patient utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddPatient", ReplyAction="http://tempuri.org/IServiceHealth/AddPatientResponse")]
        System.Threading.Tasks.Task<bool> AddPatientAsync(AlertSystem.ServiceRefHealth.Patient utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddValuesBP", ReplyAction="http://tempuri.org/IServiceHealth/AddValuesBPResponse")]
        bool AddValuesBP(AlertSystem.ServiceRefHealth.BPs values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddValuesBP", ReplyAction="http://tempuri.org/IServiceHealth/AddValuesBPResponse")]
        System.Threading.Tasks.Task<bool> AddValuesBPAsync(AlertSystem.ServiceRefHealth.BPs values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddValuesSPO", ReplyAction="http://tempuri.org/IServiceHealth/AddValuesSPOResponse")]
        bool AddValuesSPO(AlertSystem.ServiceRefHealth.SPOes values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddValuesSPO", ReplyAction="http://tempuri.org/IServiceHealth/AddValuesSPOResponse")]
        System.Threading.Tasks.Task<bool> AddValuesSPOAsync(AlertSystem.ServiceRefHealth.SPOes values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddValuesHR", ReplyAction="http://tempuri.org/IServiceHealth/AddValuesHRResponse")]
        bool AddValuesHR(AlertSystem.ServiceRefHealth.HRs values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddValuesHR", ReplyAction="http://tempuri.org/IServiceHealth/AddValuesHRResponse")]
        System.Threading.Tasks.Task<bool> AddValuesHRAsync(AlertSystem.ServiceRefHealth.HRs values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddAlerts", ReplyAction="http://tempuri.org/IServiceHealth/AddAlertsResponse")]
        bool AddAlerts(AlertSystem.ServiceRefHealth.Alertas valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AddAlerts", ReplyAction="http://tempuri.org/IServiceHealth/AddAlertsResponse")]
        System.Threading.Tasks.Task<bool> AddAlertsAsync(AlertSystem.ServiceRefHealth.Alertas valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/ValidatePatient", ReplyAction="http://tempuri.org/IServiceHealth/ValidatePatientResponse")]
        AlertSystem.ServiceRefHealth.Patient ValidatePatient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/ValidatePatient", ReplyAction="http://tempuri.org/IServiceHealth/ValidatePatientResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Patient> ValidatePatientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listActivePatient", ReplyAction="http://tempuri.org/IServiceHealth/listActivePatientResponse")]
        AlertSystem.ServiceRefHealth.Patient[] listActivePatient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listActivePatient", ReplyAction="http://tempuri.org/IServiceHealth/listActivePatientResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Patient[]> listActivePatientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listPatient", ReplyAction="http://tempuri.org/IServiceHealth/listPatientResponse")]
        AlertSystem.ServiceRefHealth.Patient[] listPatient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listPatient", ReplyAction="http://tempuri.org/IServiceHealth/listPatientResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Patient[]> listPatientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listPatientWithAlertsBP", ReplyAction="http://tempuri.org/IServiceHealth/listPatientWithAlertsBPResponse")]
        AlertSystem.ServiceRefHealth.BPs[] listPatientWithAlertsBP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listPatientWithAlertsBP", ReplyAction="http://tempuri.org/IServiceHealth/listPatientWithAlertsBPResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.BPs[]> listPatientWithAlertsBPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listPatientWithAlertsSPO", ReplyAction="http://tempuri.org/IServiceHealth/listPatientWithAlertsSPOResponse")]
        AlertSystem.ServiceRefHealth.SPOes[] listPatientWithAlertsSPO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listPatientWithAlertsSPO", ReplyAction="http://tempuri.org/IServiceHealth/listPatientWithAlertsSPOResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.SPOes[]> listPatientWithAlertsSPOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listPatientWithAlertsHR", ReplyAction="http://tempuri.org/IServiceHealth/listPatientWithAlertsHRResponse")]
        AlertSystem.ServiceRefHealth.HRs[] listPatientWithAlertsHR();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listPatientWithAlertsHR", ReplyAction="http://tempuri.org/IServiceHealth/listPatientWithAlertsHRResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.HRs[]> listPatientWithAlertsHRAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertas", ReplyAction="http://tempuri.org/IServiceHealth/listAlertasResponse")]
        AlertSystem.ServiceRefHealth.Alertas[] listAlertas(System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertas", ReplyAction="http://tempuri.org/IServiceHealth/listAlertasResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Alertas[]> listAlertasAsync(System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertasUtente", ReplyAction="http://tempuri.org/IServiceHealth/listAlertasUtenteResponse")]
        AlertSystem.ServiceRefHealth.Alertas[] listAlertasUtente(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertasUtente", ReplyAction="http://tempuri.org/IServiceHealth/listAlertasUtenteResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Alertas[]> listAlertasUtenteAsync(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listBPs", ReplyAction="http://tempuri.org/IServiceHealth/listBPsResponse")]
        AlertSystem.ServiceRefHealth.BPs[] listBPs(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listBPs", ReplyAction="http://tempuri.org/IServiceHealth/listBPsResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.BPs[]> listBPsAsync(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listSPOes", ReplyAction="http://tempuri.org/IServiceHealth/listSPOesResponse")]
        AlertSystem.ServiceRefHealth.SPOes[] listSPOes(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listSPOes", ReplyAction="http://tempuri.org/IServiceHealth/listSPOesResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.SPOes[]> listSPOesAsync(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listHRs", ReplyAction="http://tempuri.org/IServiceHealth/listHRsResponse")]
        AlertSystem.ServiceRefHealth.HRs[] listHRs(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listHRs", ReplyAction="http://tempuri.org/IServiceHealth/listHRsResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.HRs[]> listHRsAsync(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertsBPs", ReplyAction="http://tempuri.org/IServiceHealth/listAlertsBPsResponse")]
        AlertSystem.ServiceRefHealth.BPs[] listAlertsBPs(System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertsBPs", ReplyAction="http://tempuri.org/IServiceHealth/listAlertsBPsResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.BPs[]> listAlertsBPsAsync(System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertsHRs", ReplyAction="http://tempuri.org/IServiceHealth/listAlertsHRsResponse")]
        AlertSystem.ServiceRefHealth.HRs[] listAlertsHRs(System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertsHRs", ReplyAction="http://tempuri.org/IServiceHealth/listAlertsHRsResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.HRs[]> listAlertsHRsAsync(System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertsSPOes", ReplyAction="http://tempuri.org/IServiceHealth/listAlertsSPOesResponse")]
        AlertSystem.ServiceRefHealth.SPOes[] listAlertsSPOes(System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listAlertsSPOes", ReplyAction="http://tempuri.org/IServiceHealth/listAlertsSPOesResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.SPOes[]> listAlertsSPOesAsync(System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listUserAlertsBPs", ReplyAction="http://tempuri.org/IServiceHealth/listUserAlertsBPsResponse")]
        AlertSystem.ServiceRefHealth.BPs[] listUserAlertsBPs(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listUserAlertsBPs", ReplyAction="http://tempuri.org/IServiceHealth/listUserAlertsBPsResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.BPs[]> listUserAlertsBPsAsync(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listUserAlertsHRs", ReplyAction="http://tempuri.org/IServiceHealth/listUserAlertsHRsResponse")]
        AlertSystem.ServiceRefHealth.HRs[] listUserAlertsHRs(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listUserAlertsHRs", ReplyAction="http://tempuri.org/IServiceHealth/listUserAlertsHRsResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.HRs[]> listUserAlertsHRsAsync(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listUserAlertsSPOes", ReplyAction="http://tempuri.org/IServiceHealth/listUserAlertsSPOesResponse")]
        AlertSystem.ServiceRefHealth.SPOes[] listUserAlertsSPOes(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/listUserAlertsSPOes", ReplyAction="http://tempuri.org/IServiceHealth/listUserAlertsSPOesResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.SPOes[]> listUserAlertsSPOesAsync(int sns, System.DateTime di, System.DateTime df);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AlterPatient", ReplyAction="http://tempuri.org/IServiceHealth/AlterPatientResponse")]
        bool AlterPatient(AlertSystem.ServiceRefHealth.Patient utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/AlterPatient", ReplyAction="http://tempuri.org/IServiceHealth/AlterPatientResponse")]
        System.Threading.Tasks.Task<bool> AlterPatientAsync(AlertSystem.ServiceRefHealth.Patient utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/ActivatePatient", ReplyAction="http://tempuri.org/IServiceHealth/ActivatePatientResponse")]
        bool ActivatePatient(AlertSystem.ServiceRefHealth.Patient utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/ActivatePatient", ReplyAction="http://tempuri.org/IServiceHealth/ActivatePatientResponse")]
        System.Threading.Tasks.Task<bool> ActivatePatientAsync(AlertSystem.ServiceRefHealth.Patient utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/GetData", ReplyAction="http://tempuri.org/IServiceHealth/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/GetData", ReplyAction="http://tempuri.org/IServiceHealth/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceHealth/GetDataUsingDataContractResponse")]
        AlertSystem.ServiceRefHealth.CompositeType GetDataUsingDataContract(AlertSystem.ServiceRefHealth.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHealth/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceHealth/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.CompositeType> GetDataUsingDataContractAsync(AlertSystem.ServiceRefHealth.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHealthChannel : AlertSystem.ServiceRefHealth.IServiceHealth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHealthClient : System.ServiceModel.ClientBase<AlertSystem.ServiceRefHealth.IServiceHealth>, AlertSystem.ServiceRefHealth.IServiceHealth {
        
        public ServiceHealthClient() {
        }
        
        public ServiceHealthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHealthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHealthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHealthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddPatient(AlertSystem.ServiceRefHealth.Patient utente) {
            return base.Channel.AddPatient(utente);
        }
        
        public System.Threading.Tasks.Task<bool> AddPatientAsync(AlertSystem.ServiceRefHealth.Patient utente) {
            return base.Channel.AddPatientAsync(utente);
        }
        
        public bool AddValuesBP(AlertSystem.ServiceRefHealth.BPs values) {
            return base.Channel.AddValuesBP(values);
        }
        
        public System.Threading.Tasks.Task<bool> AddValuesBPAsync(AlertSystem.ServiceRefHealth.BPs values) {
            return base.Channel.AddValuesBPAsync(values);
        }
        
        public bool AddValuesSPO(AlertSystem.ServiceRefHealth.SPOes values) {
            return base.Channel.AddValuesSPO(values);
        }
        
        public System.Threading.Tasks.Task<bool> AddValuesSPOAsync(AlertSystem.ServiceRefHealth.SPOes values) {
            return base.Channel.AddValuesSPOAsync(values);
        }
        
        public bool AddValuesHR(AlertSystem.ServiceRefHealth.HRs values) {
            return base.Channel.AddValuesHR(values);
        }
        
        public System.Threading.Tasks.Task<bool> AddValuesHRAsync(AlertSystem.ServiceRefHealth.HRs values) {
            return base.Channel.AddValuesHRAsync(values);
        }
        
        public bool AddAlerts(AlertSystem.ServiceRefHealth.Alertas valores) {
            return base.Channel.AddAlerts(valores);
        }
        
        public System.Threading.Tasks.Task<bool> AddAlertsAsync(AlertSystem.ServiceRefHealth.Alertas valores) {
            return base.Channel.AddAlertsAsync(valores);
        }
        
        public AlertSystem.ServiceRefHealth.Patient ValidatePatient(int id) {
            return base.Channel.ValidatePatient(id);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Patient> ValidatePatientAsync(int id) {
            return base.Channel.ValidatePatientAsync(id);
        }
        
        public AlertSystem.ServiceRefHealth.Patient[] listActivePatient() {
            return base.Channel.listActivePatient();
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Patient[]> listActivePatientAsync() {
            return base.Channel.listActivePatientAsync();
        }
        
        public AlertSystem.ServiceRefHealth.Patient[] listPatient() {
            return base.Channel.listPatient();
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Patient[]> listPatientAsync() {
            return base.Channel.listPatientAsync();
        }
        
        public AlertSystem.ServiceRefHealth.BPs[] listPatientWithAlertsBP() {
            return base.Channel.listPatientWithAlertsBP();
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.BPs[]> listPatientWithAlertsBPAsync() {
            return base.Channel.listPatientWithAlertsBPAsync();
        }
        
        public AlertSystem.ServiceRefHealth.SPOes[] listPatientWithAlertsSPO() {
            return base.Channel.listPatientWithAlertsSPO();
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.SPOes[]> listPatientWithAlertsSPOAsync() {
            return base.Channel.listPatientWithAlertsSPOAsync();
        }
        
        public AlertSystem.ServiceRefHealth.HRs[] listPatientWithAlertsHR() {
            return base.Channel.listPatientWithAlertsHR();
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.HRs[]> listPatientWithAlertsHRAsync() {
            return base.Channel.listPatientWithAlertsHRAsync();
        }
        
        public AlertSystem.ServiceRefHealth.Alertas[] listAlertas(System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertas(di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Alertas[]> listAlertasAsync(System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertasAsync(di, df);
        }
        
        public AlertSystem.ServiceRefHealth.Alertas[] listAlertasUtente(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertasUtente(sns, di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.Alertas[]> listAlertasUtenteAsync(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertasUtenteAsync(sns, di, df);
        }
        
        public AlertSystem.ServiceRefHealth.BPs[] listBPs(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listBPs(sns, di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.BPs[]> listBPsAsync(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listBPsAsync(sns, di, df);
        }
        
        public AlertSystem.ServiceRefHealth.SPOes[] listSPOes(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listSPOes(sns, di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.SPOes[]> listSPOesAsync(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listSPOesAsync(sns, di, df);
        }
        
        public AlertSystem.ServiceRefHealth.HRs[] listHRs(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listHRs(sns, di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.HRs[]> listHRsAsync(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listHRsAsync(sns, di, df);
        }
        
        public AlertSystem.ServiceRefHealth.BPs[] listAlertsBPs(System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertsBPs(di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.BPs[]> listAlertsBPsAsync(System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertsBPsAsync(di, df);
        }
        
        public AlertSystem.ServiceRefHealth.HRs[] listAlertsHRs(System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertsHRs(di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.HRs[]> listAlertsHRsAsync(System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertsHRsAsync(di, df);
        }
        
        public AlertSystem.ServiceRefHealth.SPOes[] listAlertsSPOes(System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertsSPOes(di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.SPOes[]> listAlertsSPOesAsync(System.DateTime di, System.DateTime df) {
            return base.Channel.listAlertsSPOesAsync(di, df);
        }
        
        public AlertSystem.ServiceRefHealth.BPs[] listUserAlertsBPs(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listUserAlertsBPs(sns, di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.BPs[]> listUserAlertsBPsAsync(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listUserAlertsBPsAsync(sns, di, df);
        }
        
        public AlertSystem.ServiceRefHealth.HRs[] listUserAlertsHRs(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listUserAlertsHRs(sns, di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.HRs[]> listUserAlertsHRsAsync(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listUserAlertsHRsAsync(sns, di, df);
        }
        
        public AlertSystem.ServiceRefHealth.SPOes[] listUserAlertsSPOes(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listUserAlertsSPOes(sns, di, df);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.SPOes[]> listUserAlertsSPOesAsync(int sns, System.DateTime di, System.DateTime df) {
            return base.Channel.listUserAlertsSPOesAsync(sns, di, df);
        }
        
        public bool AlterPatient(AlertSystem.ServiceRefHealth.Patient utente) {
            return base.Channel.AlterPatient(utente);
        }
        
        public System.Threading.Tasks.Task<bool> AlterPatientAsync(AlertSystem.ServiceRefHealth.Patient utente) {
            return base.Channel.AlterPatientAsync(utente);
        }
        
        public bool ActivatePatient(AlertSystem.ServiceRefHealth.Patient utente) {
            return base.Channel.ActivatePatient(utente);
        }
        
        public System.Threading.Tasks.Task<bool> ActivatePatientAsync(AlertSystem.ServiceRefHealth.Patient utente) {
            return base.Channel.ActivatePatientAsync(utente);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AlertSystem.ServiceRefHealth.CompositeType GetDataUsingDataContract(AlertSystem.ServiceRefHealth.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<AlertSystem.ServiceRefHealth.CompositeType> GetDataUsingDataContractAsync(AlertSystem.ServiceRefHealth.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
